server:
    port: 9093
    servlet:
      context-path: /ui2
#    session:
#      cookie:
#        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9091/auth/oauth/token
      userAuthorizationUri: http://localhost:9091/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:9091/auth/user/me
spring:
  thymeleaf:
    cache: false