itsnow:
  client:
    clientId: test
    clientSecret: test
    accessTokenUri: http://localhost:18001/auth/oauth/token
    userAuthorizationUri: http://localhost:18001/auth/oauth/authorize

  resource:
    userInfoUri: http://localhost:18002/user/name/test

logging:
  level:
    org.springframework.security: DEBUG
